// Generated by Agentic QE Platform - MVP (automation script agent).
// Business rule: BR-005 - Commissionable room revenue
// Type of testing: Regression testing
// Statement: Commissionable room revenue excludes taxes, resort fees and ancillary charges.
// Requirement: REQ-005 v1; sources: COM-10
// Covers test cases: TC-F-004 (Taxes, resort fees and ancillaries are excluded from commissionable revenue)
// Skills applied: automation-script-conventions, incremental-merge, testing-regression, traceability-handover
// Self-contained: needs only @playwright/test and a baseURL pointing at the system under test.
const { test, expect } = require('@playwright/test');

let dictionary = null;

function summarise(data) {
  if (data && data.reservation) {
    const attrs = Object.keys(data.reservation).length;
    return { reservation: `<${attrs} attributes>`, overrides: data.overrides || null };
  }
  return data ?? null;
}

async function call(request, testInfo, method, url, data, overrides) {
  const res = await request.fetch(url, { method, data });
  let body = null;
  try { body = await res.json(); } catch { body = null; }
  const shown = body && Array.isArray(body.attributes) ? { ...body, attributes: `<${body.attributes.length} attributes>` } : body;
  await testInfo.attach(`${method} ${url}`, {
    body: JSON.stringify({ request: { method, url, data: summarise(data && overrides ? { ...data, overrides } : data) }, response: { status: res.status(), body: shown } }, null, 2),
    contentType: 'application/json',
  });
  return { status: res.status(), body };
}

const TEST_DATA = require('path').join(__dirname, '..', 'test-data');

/** The test data agent's data set for this case (test-data/<case key>.json), when present. */
function dataSet(testInfo) {
  const key = testInfo && (testInfo.title.match(/^(TC-[FN]-\d+)\s/) || [])[1];
  const file = key && require('path').join(TEST_DATA, `${key}.json`);
  return file && require('fs').existsSync(file) ? JSON.parse(require('fs').readFileSync(file, 'utf8')) : null;
}

async function reservation(request, overrides, testInfo) {
  const set = dataSet(testInfo);
  if (set) return { ...set.reservation, ...overrides };
  if (!dictionary) dictionary = await (await request.get('/api/data-dictionary')).json();
  const res = {};
  for (const a of dictionary.attributes) res[a.name] = a.example;
  return { ...res, ...overrides };
}

async function quote(request, testInfo, overrides) {
  return call(request, testInfo, 'POST', '/api/commission/quote', { reservation: await reservation(request, overrides, testInfo) }, overrides);
}

test("TC-F-004 Taxes, resort fees and ancillaries are excluded from commissionable revenue", async ({ request }, testInfo) => {
  const r = await quote(request, testInfo, {"reservation.status":"CONFIRMED","channel.bookingChannel":"DIRECT","stay.nights":3,"rate.planCategory":"BAR","room.roomCount":1,"payment.loyaltyPointsRedemption":false,"revenue.totalAmount":1000,"revenue.taxAmount":120,"revenue.resortFeeAmount":30,"revenue.ancillaryAmount":50});
  expect(r.status).toBe(200);
  expect(r.body.commissionableRevenue).toBe(800);
});
