// Generated by Agentic QE Platform - MVP (automation script agent).
// Business rule: BR-124 - Resend rate limit
// Type of testing: Regression testing
// Statement: A confirmation can be resent at most 5 times per booking in 24 hours.
// Requirement: REQ-124 v2; sources: AQPI-35
// Covers test cases: TC-F-115 (The 6th resend within 24 hours is refused)
// Superseded (v1): A confirmation can be resent at most 3 times per booking in 24 hours.
// Skills applied: automation-script-conventions, incremental-merge, testing-regression, traceability-handover
// Self-contained: needs only @playwright/test and the hotel service URLs (config metadata.services).
const { test, expect } = require('@playwright/test');

const TEST_DATA = require('path').join(__dirname, '..', 'test-data');
const SERVICES = ['hotel-service', 'search-service', 'offer-service', 'cart-service', 'reservation-service', 'notification-service'];
const OPS = { 'X-Operator-Role': 'SUPPORT' };

/** The test data agent's data set for this case (test-data/<case key>.json). */
function dataSet(testInfo) {
  const key = testInfo && (testInfo.title.match(/^(TC-[FN]-\d+)\s/) || [])[1];
  const file = key && require('path').join(TEST_DATA, `${key}.json`);
  return file && require('fs').existsSync(file) ? JSON.parse(require('fs').readFileSync(file, 'utf8')) : null;
}

/** The complete booking the test data agent generated for this case from the hotel data dictionary. */
function booking(testInfo) {
  const set = dataSet(testInfo);
  if (!set || !set.reservation) throw new Error('No test data set for this case: the test data agent writes test-data/<case key>.json before execution.');
  return set.reservation;
}

function serviceUrl(testInfo, name) {
  const url = (testInfo.config.metadata.services || {})[name];
  if (!url) throw new Error(`No URL for ${name}: run this spec against the hotel booking platform.`);
  return url;
}

async function call(request, testInfo, service, method, p, data, headers = {}) {
  const url = serviceUrl(testInfo, service) + p;
  const res = await request.fetch(url, { method, data, headers, failOnStatusCode: false });
  const text = await res.text();
  let body = null;
  try { body = JSON.parse(text); } catch { body = text || null; }
  await testInfo.attach(`${method} ${service}${p}`, {
    body: JSON.stringify({ request: { method, url, headers, data: data ?? null }, response: { status: res.status(), correlationId: res.headers()['x-correlation-id'] || null, body } }, null, 2),
    contentType: 'application/json',
  });
  return { status: res.status(), body, headers: res.headers() };
}

const RESETTABLE = SERVICES.filter((s) => s !== 'search-service');

async function fresh(request, testInfo) {
  for (const s of RESETTABLE) await request.post(serviceUrl(testInfo, s) + '/api/admin/reset');
}

const day = (offset) => { const d = new Date(); d.setUTCHours(0, 0, 0, 0); d.setUTCDate(d.getUTCDate() + offset); return d.toISOString().slice(0, 10); };

function criteria(b) {
  const from = Number(b['stay.checkInOffsetDays']);
  return { destination: b['search.destination'], checkIn: day(from), checkOut: day(from + Number(b['stay.nights'])),
    rooms: b['occupancy.rooms'], adults: b['occupancy.adults'], children: b['occupancy.children'] };
}

function selection(b) {
  const c = criteria(b);
  return { hotelId: b['selection.hotelId'], roomCode: b['selection.roomCode'], ratePlanCode: b['selection.ratePlanCode'],
    checkIn: c.checkIn, checkOut: c.checkOut, rooms: c.rooms, adults: c.adults, children: c.children };
}

function offerContext(b) {
  const c = criteria(b);
  return { hotelId: b['selection.hotelId'], destination: c.destination, checkIn: c.checkIn, checkOut: c.checkOut, roomCode: b['selection.roomCode'],
    ratePlanCode: b['selection.ratePlanCode'], adults: c.adults, children: c.children, currency: 'USD' };
}

const search = (request, testInfo, b, headers) => call(request, testInfo, 'search-service', 'POST', '/api/searches', criteria(b), headers);
const createCart = (request, testInfo, b) => call(request, testInfo, 'cart-service', 'POST', '/api/carts', selection(b));
const addExtra = (request, testInfo, cartId, code, quantity = 1) => call(request, testInfo, 'cart-service', 'POST', `/api/carts/${cartId}/ancillaries`, { code, quantity: Number(quantity) || 1 });
const setInventory = (request, testInfo, hotelId, rooms) => call(request, testInfo, 'hotel-service', 'PUT', '/api/admin/inventory', { hotelId, rooms });
const setRate = (request, testInfo, hotelId, roomCode, ratePlan, nightly) => call(request, testInfo, 'hotel-service', 'PUT', `/api/admin/hotels/${hotelId}/rooms/${roomCode}/rates/${ratePlan}`, { nightly });

function reservationRequest(cartId, b) {
  return { cartId, guest: { firstName: b['guest.firstName'], lastName: b['guest.lastName'], email: b['guest.email'], phone: b['guest.phone'] || null, arrivalTime: b['guest.arrivalTime'] || null },
    paymentToken: b['payment.token'], privacyNoticeAccepted: b['consent.privacyNoticeAccepted'], marketingOptIn: Boolean(b['consent.marketingOptIn']), locale: b['notification.locale'] || null };
}

let keySeq = 0;
const idempotencyKey = (b, testInfo) => `${b['request.idempotencyKeyPrefix']}-${testInfo.testId.slice(-8)}-${keySeq += 1}`;

function reserve(request, testInfo, cartId, b, key = idempotencyKey(b, testInfo), headers = {}) {
  return call(request, testInfo, 'reservation-service', 'POST', '/api/reservations', reservationRequest(cartId, b), { ...(key ? { 'Idempotency-Key': key } : {}), ...headers });
}

test("TC-F-115 The 6th resend within 24 hours is refused", async ({ request }, testInfo) => {
  const b = booking(testInfo);
  await fresh(request, testInfo);
  const cart = await createCart(request, testInfo, b);
  expect(cart.status).toBe(201);
  const r = await reserve(request, testInfo, cart.body.cartId, b);
  for (let i = 0; i < 5; i += 1) expect((await call(request, testInfo, 'notification-service', 'POST', '/api/confirmations/resend', { confirmationNumber: r.body.confirmationNumber, lastName: b['guest.lastName'] })).status).toBe(202);
  const over = await call(request, testInfo, 'notification-service', 'POST', '/api/confirmations/resend', { confirmationNumber: r.body.confirmationNumber, lastName: b['guest.lastName'] });
  expect(over.status).toBe(429);
  const pay = await call(request, testInfo, 'reservation-service', 'GET', '/api/ops/payments', undefined, OPS);
  expect(pay.body).toHaveLength(1);
});
