// Generated by Agentic QE Platform - MVP (automation script agent).
// Business rule: BR-002 - Advisor commission statement (UI)
// Type of testing: Regression testing
// Statement: Travel advisors can view the commission breakdown for a reservation online.
// Requirement: REQ-002 v1; sources: COM-1
// Covers test cases: TC-F-002 (Advisor views the commission breakdown on the commission statement page)
// Skills applied: automation-script-conventions, incremental-merge, testing-regression, traceability-handover
// Self-contained: needs only @playwright/test and a baseURL pointing at the system under test.
const { test, expect } = require('@playwright/test');

let dictionary = null;

function summarise(data) {
  if (data && data.reservation) {
    const attrs = Object.keys(data.reservation).length;
    return { reservation: `<${attrs} attributes>`, overrides: data.overrides || null };
  }
  return data ?? null;
}

async function call(request, testInfo, method, url, data, overrides) {
  const res = await request.fetch(url, { method, data });
  let body = null;
  try { body = await res.json(); } catch { body = null; }
  const shown = body && Array.isArray(body.attributes) ? { ...body, attributes: `<${body.attributes.length} attributes>` } : body;
  await testInfo.attach(`${method} ${url}`, {
    body: JSON.stringify({ request: { method, url, data: summarise(data && overrides ? { ...data, overrides } : data) }, response: { status: res.status(), body: shown } }, null, 2),
    contentType: 'application/json',
  });
  return { status: res.status(), body };
}

async function reservation(request, overrides) {
  if (!dictionary) dictionary = await (await request.get('/api/data-dictionary')).json();
  const res = {};
  for (const a of dictionary.attributes) res[a.name] = a.example;
  return { ...res, ...overrides };
}

async function quote(request, testInfo, overrides) {
  return call(request, testInfo, 'POST', '/api/commission/quote', { reservation: await reservation(request, overrides) }, overrides);
}

test("TC-F-002 Advisor views the commission breakdown on the commission statement page", async ({ page, request }, testInfo) => {
  const created = await call(request, testInfo, 'POST', '/api/reservations', { reservation: await reservation(request, {"reservation.status":"CONFIRMED","channel.bookingChannel":"GDS","stay.nights":3,"rate.planCategory":"BAR","room.roomCount":1,"payment.loyaltyPointsRedemption":false,"revenue.totalAmount":1000,"revenue.taxAmount":120,"revenue.resortFeeAmount":30,"revenue.ancillaryAmount":50}) });
  expect(created.status).toBe(201);
  await page.goto('/');
  await page.fill('#reservation-id', created.body.id);
  await page.click('#show');
  await expect(page.locator('#statement')).toContainText('Commission breakdown');
  await expect(page.locator('#statement')).toContainText('Base commission');
  await expect(page.locator('#statement')).toContainText('Total commission');
  await testInfo.attach('screenshot', { body: await page.screenshot(), contentType: 'image/png' });
});
