// Generated by Agentic QE Platform - MVP (automation script agent).
// Business rule: BR-015 - Group flat rate
// Statement: Group reservations of 10 or more rooms are commissioned at a flat 8%.
// Requirement: REQ-015 v1; sources: COM-20
// Covers test cases: TC-F-015 (A group of 10 rooms is commissioned at a flat 8%); TC-F-016 (9 rooms keep the transient base rate)
// Skills applied: automation-script-conventions, incremental-merge, traceability-handover
// Self-contained: needs only @playwright/test and a baseURL pointing at the system under test.
const { test, expect } = require('@playwright/test');

let dictionary = null;

function summarise(data) {
  if (data && data.reservation) {
    const attrs = Object.keys(data.reservation).length;
    return { reservation: `<${attrs} attributes>`, overrides: data.overrides || null };
  }
  return data ?? null;
}

async function call(request, testInfo, method, url, data, overrides) {
  const res = await request.fetch(url, { method, data });
  let body = null;
  try { body = await res.json(); } catch { body = null; }
  const shown = body && Array.isArray(body.attributes) ? { ...body, attributes: `<${body.attributes.length} attributes>` } : body;
  await testInfo.attach(`${method} ${url}`, {
    body: JSON.stringify({ request: { method, url, data: summarise(data && overrides ? { ...data, overrides } : data) }, response: { status: res.status(), body: shown } }, null, 2),
    contentType: 'application/json',
  });
  return { status: res.status(), body };
}

async function reservation(request, overrides) {
  if (!dictionary) dictionary = await (await request.get('/api/data-dictionary')).json();
  const res = {};
  for (const a of dictionary.attributes) res[a.name] = a.example;
  return { ...res, ...overrides };
}

async function quote(request, testInfo, overrides) {
  return call(request, testInfo, 'POST', '/api/commission/quote', { reservation: await reservation(request, overrides) }, overrides);
}

test("TC-F-015 A group of 10 rooms is commissioned at a flat 8%", async ({ request }, testInfo) => {
  const r = await quote(request, testInfo, {"reservation.status":"CONFIRMED","channel.bookingChannel":"DIRECT","stay.nights":3,"rate.planCategory":"BAR","room.roomCount":10,"payment.loyaltyPointsRedemption":false,"revenue.totalAmount":1000,"revenue.taxAmount":120,"revenue.resortFeeAmount":30,"revenue.ancillaryAmount":50});
  expect(r.status).toBe(200);
  expect(r.body.effectiveRatePct).toBe(8);
  expect(r.body.commission).toBe(64);
});

test("TC-F-016 9 rooms keep the transient base rate", async ({ request }, testInfo) => {
  const r = await quote(request, testInfo, {"reservation.status":"CONFIRMED","channel.bookingChannel":"DIRECT","stay.nights":3,"rate.planCategory":"BAR","room.roomCount":9,"payment.loyaltyPointsRedemption":false,"revenue.totalAmount":1000,"revenue.taxAmount":120,"revenue.resortFeeAmount":30,"revenue.ancillaryAmount":50});
  expect(r.status).toBe(200);
  expect(r.body.effectiveRatePct).toBe(10);
  expect(r.body.commission).toBe(80);
});
