'use strict';
// Execution agent: really runs the generated Playwright specs, headless, against the bundled SUT,
// and maps the Playwright JSON report back to test cases. Nothing here is simulated.
const fs = require('fs');
const path = require('path');
const { spawn } = require('child_process');
const { startSut, BUILDS, DEFAULT_BUILD } = require('../sut/server');

const ROOT = path.join(__dirname, '..');
const PW_CLI = require.resolve('@playwright/test/cli');
const PW_VERSION = require('@playwright/test/package.json').version;

const stripAnsi = (s) => String(s || '').replace(/\u001b\[[0-9;]*m/g, '');

function writeRunFiles(runDir, scripts, baseURL) {
  const specDir = path.join(runDir, 'specs');
  fs.rmSync(specDir, { recursive: true, force: true });
  fs.mkdirSync(specDir, { recursive: true });
  for (const s of scripts) fs.writeFileSync(path.join(specDir, s.file), s.code);
  const config = `// Generated by Agentic QE Platform - MVP (execution agent)
module.exports = {
  testDir: ${JSON.stringify(specDir)},
  testMatch: '**/*.spec.js',
  timeout: 20000,
  retries: 0,
  workers: 2,
  outputDir: ${JSON.stringify(path.join(runDir, 'test-results'))},
  reporter: [['json', { outputFile: ${JSON.stringify(path.join(runDir, 'playwright-report.json'))} }]],
  use: { baseURL: ${JSON.stringify(baseURL)}, headless: true, screenshot: 'only-on-failure', trace: 'off' },
};
`;
  const configFile = path.join(runDir, 'playwright.config.js');
  fs.writeFileSync(configFile, config);
  return configFile;
}

function runPlaywright(configFile, cwd) {
  return new Promise((resolve) => {
    const args = [PW_CLI, 'test', '--config', configFile];
    const child = spawn(process.execPath, args, {
      cwd,
      env: { ...process.env, NODE_PATH: path.join(ROOT, 'node_modules'), FORCE_COLOR: '0', PLAYWRIGHT_JSON_OUTPUT_NAME: '' },
    });
    let out = '';
    child.stdout.on('data', (d) => { out += d; });
    child.stderr.on('data', (d) => { out += d; });
    child.on('close', (code) => resolve({ exitCode: code, output: out, command: `npx playwright test --config ${path.relative(ROOT, configFile)}` }));
  });
}

function collectSpecs(suite, file, out) {
  for (const spec of suite.specs || []) out.push({ file: spec.file || suite.file || file, spec });
  for (const child of suite.suites || []) collectSpecs(child, child.file || file, out);
  return out;
}

function parseError(err) {
  if (!err) return null;
  const message = stripAnsi(err.message);
  const expected = message.match(/Expected(?: pattern| substring| string| value)?:\s*(.*)/);
  const received = message.match(/Received(?: string| value)?:\s*(.*)/);
  const snippet = stripAnsi(err.snippet || '');
  const failingLine = snippet.split('\n').find((l) => /^\s*>/.test(l));
  return {
    message: message.split('\n').slice(0, 12).join('\n'),
    expected: expected ? expected[1].trim() : null,
    actual: received ? received[1].trim() : null,
    assertion: failingLine ? failingLine.replace(/^\s*>\s*\d+\s*\|\s?/, '').trim() : message.split('\n')[0],
    location: err.location ? `${path.basename(err.location.file)}:${err.location.line}:${err.location.column}` : null,
  };
}

/** Maps a Playwright JSON report to per-test-case results. Titles start with the case key: "TC-F-003 ...". */
function mapReport(report, testCases, { evidenceDir = null } = {}) {
  const found = new Map();
  for (const suite of report.suites || []) {
    for (const { file, spec } of collectSpecs(suite, suite.file, [])) {
      const m = spec.title.match(/^\[?(TC-[FN]-\d+|[A-Z]+-T\d+)\]?(?:\s|$)/);
      if (!m) continue;
      const t = spec.tests[0];
      const r = t.results[t.results.length - 1] || {};
      const evidence = [];
      (r.attachments || []).forEach((a, i) => {
        if (!evidenceDir) return;
        const ext = a.contentType === 'image/png' ? 'png' : a.contentType === 'application/json' ? 'json' : 'txt';
        const name = `${m[1]}-${i + 1}.${ext}`;
        let data = null;
        if (a.body) data = Buffer.from(a.body, 'base64');
        else if (a.path && fs.existsSync(a.path)) data = fs.readFileSync(a.path);
        if (!data) return;
        fs.mkdirSync(evidenceDir, { recursive: true });
        fs.writeFileSync(path.join(evidenceDir, name), data);
        evidence.push({ name: a.name, file: name, contentType: a.contentType });
      });
      found.set(m[1], {
        status: r.status === 'passed' ? 'passed' : r.status === 'skipped' ? 'skipped' : 'failed',
        playwrightStatus: r.status,
        duration: r.duration ?? 0,
        startTime: r.startTime || null,
        file: path.basename(file || ''),
        title: spec.title,
        error: r.status === 'passed' ? null : parseError(r.error || (r.errors || [])[0]),
        evidence,
      });
    }
  }
  return testCases.map((tc) => {
    const base = { key: tc.key, requirementId: tc.requirementId, ruleId: tc.ruleId || null, name: tc.name, type: tc.type, scriptFile: tc.scriptFile };
    if (tc.automation !== 'Automated') return { ...base, status: 'not-run', reason: 'Manual test case - not automated, not executed', duration: 0, error: null, evidence: [] };
    const hit = found.get(tc.key);
    if (!hit) return { ...base, status: 'not-run', reason: 'Automated case not present in the Playwright report', duration: 0, error: null, evidence: [] };
    return { ...base, ...hit };
  });
}

function summarise(results) {
  const s = { total: results.length, executed: 0, passed: 0, failed: 0, skipped: 0, notRun: 0, durationMs: 0 };
  for (const r of results) {
    if (r.status === 'not-run') { s.notRun += 1; continue; }
    s.executed += 1;
    s.durationMs += r.duration || 0;
    if (r.status === 'passed') s.passed += 1;
    else if (r.status === 'failed') s.failed += 1;
    else s.skipped += 1;
  }
  s.passRate = s.executed ? Math.round((s.passed / s.executed) * 1000) / 10 : 0;
  return s;
}

/** Starts the SUT, writes specs + config, runs Playwright headless, parses and maps the JSON report. */
async function executeSuite({ scripts, testCases, runDir, sutBuild = DEFAULT_BUILD }) {
  fs.mkdirSync(runDir, { recursive: true });
  const sut = await startSut({ version: sutBuild });
  const startedAt = new Date().toISOString();
  let run;
  try {
    const configFile = writeRunFiles(runDir, scripts, sut.url);
    run = await runPlaywright(configFile, runDir);
  } finally {
    await sut.close();
  }
  const finishedAt = new Date().toISOString();
  const reportFile = path.join(runDir, 'playwright-report.json');
  fs.writeFileSync(path.join(runDir, 'playwright-output.txt'), run.output);
  if (!fs.existsSync(reportFile)) {
    const err = new Error(`Playwright produced no JSON report (exit ${run.exitCode}): ${stripAnsi(run.output).slice(-800)}`);
    err.code = 'NO_REPORT';
    throw err;
  }
  const report = JSON.parse(fs.readFileSync(reportFile, 'utf8'));
  const results = mapReport(report, testCases, { evidenceDir: path.join(runDir, 'evidence') });
  return {
    executed: true,
    tool: `Playwright ${PW_VERSION} (headless Chromium, JSON reporter)`,
    command: run.command,
    exitCode: run.exitCode,
    sut: { build: sutBuild, url: sut.url, name: `Aurora commission engine, bundled copy of branch ${sutBuild} (samples/commission-engine/${BUILDS[sutBuild]})` },
    startedAt, finishedAt,
    reportFile: 'playwright-report.json',
    playwrightStats: report.stats || null,
    specFiles: scripts.map((s) => s.file),
    results,
    summary: summarise(results),
  };
}

module.exports = { executeSuite, mapReport, parseError, summarise, PW_VERSION };
